"""empty message

Revision ID: 59680006ded3
Revises: f9ebbbc4be00
Create Date: 2023-07-19 15:11:14.621218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59680006ded3'
down_revision = 'f9ebbbc4be00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('profilePic',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('profilePic',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
